#
# Brewfile for Linuxbrew
#
# :Taps ------------------------------------------------------------------------
# :Brew ------------------------------------------------------------------------
brew 'gh'
brew 'clojure/tools/clojure'
brew 'leiningen'
